### PR TITLE
Retrieve the SSL thumbprint of the peer ESXi/vCenter server

### PR DESCRIPTION
**Pull request by hubertverstraete**
The code computes the SSL thumbprint on the first request to the ESXi or vCenter server.

### CODE REVIEW

**Comment by michaelrice** [comment]
Hey @hubertverstraete Can you add some [tests](https://github.com/yavijava/yavijava/wiki/YAVIJAVA#testing)?

**Comment by michaelrice** [comment]
@hubertverstraete Also you will need to follow this work flow when submitting pull requests: https://github.com/yavijava/yavijava/wiki/Contributing#step-by-step-example

**Comment by hubertverstraete** [comment]
Hi @michaelrice 

I am thinking at adding an integration test which gets the SSL thumbprint using the openssl utility and compare it with the thumbprint computed by yavijava. This would have to be run from Linux, because Linux distro always have openssl. On Windows, you would have to install openssl. Does this sound good ? 

I've read the pull request instructions. I'll create a branch and do a new pull request with this branch.

**Comment by michaelrice** [comment]
Hi @hubertverstraete that would not be ideal. A better solution for that might be to add a variable to [this](https://github.com/yavijava/yavijava/blob/gradle/src/intTest/java/VcenterInfo.properties) file and let a user add the thumbprint as a variable, then when the test runs it wold compare to that variable. Another test that might be good is to make multiple requests and ensure your code only runs one time.

**Comment by hubertverstraete** [comment]
Closing and opening #143

**Pull request closed without merging**
