### PR TITLE
Update WSClient for #38 and #123

### LINKED ISSUE #38: Reuse SSLSocketFactory
http://sourceforge.net/p/vijava/feature-requests/24/

This part of the code has been refactored since this was reported but I dont think its really been fixed. I think its just called another way now.

> WCClient uses a new instance of SSLSocketFactory every time it connects to VC. As a result, sockets cannot be reused. There is also a small performance issue that trustAllHttpsCertificates() is executed upon each connection when it actually needs to be executed only once per the lifetime of the application.
> Suggested code changes:

``` java
private static volatile boolean initialized = false; // new code
private static void trustAllHttpsCertificates() throws NoSuchAlgorithmException, KeyManagementException {
    if (initialized) {return; }// new code
    initialized = true; // new code
    TrustManager[] trustAllCerts = new TrustManager[1]; 
    trustAllCerts[0] = new TrustAllManager(); 
    SSLContext sc = SSLContext.getInstance("SSL"); 
    sc.init(null, trustAllCerts, null); 
    HttpsURLConnection.setDefaultSSLSocketFactory(sc.getSocketFactory());
}
```

### LINKED ISSUE #123: Performance degraded with yavijava 6.0.
Hi,

We manage dvSwitch by taking its configuration backup and deploying changes.
We do configuration backup by running lot of queries. With vijava the whole operation of backup was taking 6 seconds and when we change to yavijava 6.0.01 jar , the same operation took 9 minutes.
I will try to summarize what exactly we do to take configuration backup of DVSwitch.

``` java
DistributedVirtualSwitch dvSwitch = state.dvSwitch;
DVSConfigInfo dvsCfg = dvSwitch.getConfig();
int[] vlanIds = dvSwitch.queryUsedVlanIdInDvs();
ManagedObjectReference[] uplinks = dvsCfg.getUplinkPortgroup();
String description = dvsCfg.getDescription();
String ipAddress = dvsCfg.getSwitchIpAddress();
 dvsCfg.getNumPorts()
 + dvsCfg.getMaxPorts()
+ dvsCfg.getNumStandalonePorts()
```

The above given are some methods which we trigger to get confguration of dvSwitch. We trigger many more such methods to get complete information of all dvPort groups and all ports associated with port-groups.

So if I use yavijava 6.0.01 jar it works in dvSwitch but with degraded performance. When I try to run same operation on dvSwitch which is on vSphere 5.5 it takes 9 minutes as compared to 6 seconds in case of vijava.

Kindly suggest.

### PR DESCRIPTION
**Pull request by michaelrice**
Attempt to fix issue #38 and #123 in order to reuse the SSLSocketFactory

Fixes #38
Fixes #123

Added test for the SSLSocketFactory initialization

### CODE REVIEW

**Comment by michaelrice** [comment]
Hey @scottmlaplante Can I get you to look this over before I merge? I think it looks good and all, but another set of eyes on it wouldnt hurt.

**Comment by scottmlaplante** [comment]
Hey Michael,

Sorry i was out on vacation and didnt have access to my email. Ill take 
a look tonight or tomorrow morning!

-S

**Comment by scottmlaplante** [comment]
My other concern is that the ServiceInstanceIntTest should now fail with this change. Does it still pass?

**Comment by michaelrice** [comment]
@scottmlaplante My whole environment is in turmoil right now. My main system crashed from bad memory or something the apple store has it, my lab is down from a bad MB so I honestly didnt even get a chance to run the INT tests before I merged it :disappointed: Im at wmworld this week, so maybe I could find someone while here that would have resources to let me run the tests and see. I merged it after speaking with someone over email who verified these changes fixed their issue, and Im pretty sure they were not using that custom thing you added.

**Comment by scottmlaplante** [comment]
Sorry to hear about your computer troubles. Yeah, i can see how it would fix the issue of re-creating the socket factory over and over. However, no issue would be encountered if using trust all, which is what im guessing they are using. However, there could now be a vulnerability if a server responses with a certificate that is bogus since only trust all is being used. 

I can go ahead and fix this when i have a chance tomorrow. Ill keep you posted.

**Comment by scottmlaplante** [comment]
Im working on this fix now, ill post for your review @michaelrice when its ready.

**Comment by scottmlaplante** [comment]
@michaelrice i opened a pull request to address the issue. Let me know when you have a chance to review, im sure you are busy at vmworld :-)

**Pull request merged**
