### PR TITLE
Update WSClient.java

### PR DESCRIPTION
**Pull request by michaelrice**
Attempt to fix issue #38 in order to reuse the SSLSocketFactory

### CODE REVIEW

**Comment by michaelrice** [comment]
Ive made a slight change and removed the logic from the constructor and placed it into a protected method so that we can create a test around this. @BigBeaule Would you care to take a stab at the test creation?

**Comment by BigBeaule** [comment]
Ok I should be able to do it by the end of the week!

Regards

**Comment by michaelrice** [comment]
@BigBeaule Cool. You might find this useful: https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by BigBeaule** [comment]
I don't have the write access to this new fork so I can't checkout and modify the pull request!

**Comment by michaelrice** [comment]
You can check it out using the method described in that link I shared. Once you make your changes push them to your origin and open a pull request to my branch. If you need some help please feel free to join the Gitter Chat or I am on Freenode IRC in #vijava and #pyvmomi and can help. My nick on Freenode is errr

**Comment by michaelrice** [comment]
see #117

**Pull request closed without merging**
