### PR TITLE
Included read and connection timeouts in ServiceInstance to ensure ti…

### PR DESCRIPTION
**Pull request by scottmlaplante**
…meouts occur when there are connectivity problems

### CODE REVIEW

**Comment by scottmlaplante** [comment]
Made some updates to allow connection and read timeouts to occur. We have run into cases when there are connectivity problems, connecting to the vCenter or reading data from the vCenter can stall indefinitely. Thats because the default read and connect timeouts are 0 in VIJava. So ive made some updates to improve this. Thanks!

**Comment by michaelrice** [comment]
This is fantastic! Thank you! Ill pull this down locally tonight to review it.

**Comment by michaelrice** [comment]
@scottmlaplante This looks great, works great, tests are marvelous. I cant thank you enough for your contribution. I hope to see more :100:

**Comment by scottmlaplante** [comment]
Excellent, thanks Michael! Looking forward to contributing more here!

**Pull request merged**
