### PR TITLE
Fix typo in javadoc

### PR DESCRIPTION
**Pull request by TresSheets**

### CODE REVIEW

**Comment by michaelrice** [comment]
Can you rebase this into 1 commit?

**Comment by TresSheets** [comment]
@michaelrice Not sure I did this correctly.  If not, please let me know.

**Comment by michaelrice** [comment]
@TresSheets no you made it way worse. It went from 2 to 7 now :)

**Comment by TresSheets** [comment]
@michaelrice I'm going to abandon this PR and submit a new one.

**Pull request closed without merging**
